# Site
title: 熊吉的博客小站
subtitle: sometimes code， sometimes design
description: 熊吉的博客小站
keywords:
  - 熊吉
author: LuckyBear
language: zh
timezone: Asia/Shanghai

# URL
url: https://luckybear.dev
root: /
permalink: :year/:month/:day/:title/
permalink_defaults: {}
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: []

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  auto_detect: false
  line_number: true
  tab_replace: ''
  wrap: true

# Category & Tag
default_category: uncategorized
category_map: {}
tag_map: {}

# Date / Time
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
per_page: 10
pagination_dir: page

# Generators
feed:
  type: atom
  path: atom.xml
  limit: 20

search:
  path: search.json
  field: post

# Extensions
theme: aircloud

# Markdown renderer
marked:
  prependRoot: true
  postAsset: true
  lazyload: true
